import { Injectable } from "@nestjs/common";
import { Role } from "../../domain/entities/role";
import { RoleRepository } from "../../domain/interfaces/role-repository.interface";
import { CreateRoleDto } from "../dtos/create-role.dto";

@Injectable()
export class CreateRoleUseCase {
    constructor(private readonly roleRepository: RoleRepository) {}
    
    async execute(dto: CreateRoleDto): Promise<Role | null> {
        const roleData = new Role(
            '', // Assuming ID is generated by the repository or database
            dto.role
            );
            console.log(roleData);

        return this.roleRepository.create(roleData);
    }
    }
